package tdh

var TilesForTest = []Tile{
	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},
	{Wind, East, EastWind, 31, false, false},
	{Wind, South, SouthWind, 33, false, false},
	{Wind, West, WestWind, 32, false, false},
	{Wind, North, NorthWind, 34, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},
	{Wind, East, EastWind, 31, false, false},
	{Wind, East, EastWind, 31, false, false},
	{Wind, East, EastWind, 31, false, false},
	{Wind, North, NorthWind, 34, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},
	{Wind, South, SouthWind, 33, false, false},
	{Wind, South, SouthWind, 33, false, false},
	{Wind, South, SouthWind, 33, false, false},
	{Wind, North, NorthWind, 34, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},
}

var TileWithFeng = []Tile{
	{Wind, East, EastWind, 31, false, false},
	{Wind, South, SouthWind, 33, false, false},
	{Wind, West, WestWind, 32, false, false},
	{Wind, North, NorthWind, 34, false, false},
	{Wind, Red, RedDragon, 10, false, false},
	{Wind, Green, GreenDragon, 20, false, false},
	{Wind, White, WhiteDragon, 30, false, false},

	{Wind, East, EastWind, 31, false, false},
	{Wind, South, SouthWind, 33, false, false},
	{Wind, West, WestWind, 32, false, false},
	{Wind, North, NorthWind, 34, false, false},
	{Wind, Red, RedDragon, 10, false, false},
	{Wind, Green, GreenDragon, 20, false, false},
	{Wind, White, WhiteDragon, 30, false, false},

	{Wind, East, EastWind, 31, false, false},
	{Wind, South, SouthWind, 33, false, false},
	{Wind, West, WestWind, 32, false, false},
	{Wind, North, NorthWind, 34, false, false},
	{Wind, Red, RedDragon, 10, false, false},
	{Wind, Green, GreenDragon, 20, false, false},
	{Wind, White, WhiteDragon, 30, false, false},

	{Wind, East, EastWind, 31, false, false},
	{Wind, South, SouthWind, 33, false, false},
	{Wind, West, WestWind, 32, false, false},
	{Wind, North, NorthWind, 34, false, false},
	{Wind, Red, RedDragon, 10, false, false},
	{Wind, Green, GreenDragon, 20, false, false},
	{Wind, White, WhiteDragon, 30, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},

	{Characters, One, OneOfCharacters, 1, false, false},
	{Characters, Two, TwoOfCharacters, 2, false, false},
	{Characters, Three, ThreeOfCharacters, 3, false, false},
	{Characters, Four, FourOfCharacters, 4, false, false},
	{Characters, Five, FiveOfCharacters, 5, false, false},
	{Characters, Six, SixOfCharacters, 6, false, false},
	{Characters, Seven, SevenOfCharacters, 7, false, false},
	{Characters, Eight, EightOfCharacters, 8, false, false},
	{Characters, Nine, NineOfCharacters, 9, false, false},

	{Circles, One, OneOfCircles, 11, false, false},
	{Circles, Two, TwoOfCircles, 12, false, false},
	{Circles, Three, ThreeOfCircles, 13, false, false},
	{Circles, Four, FourOfCircles, 14, false, false},
	{Circles, Five, FiveOfCircles, 15, false, false},
	{Circles, Six, SixOfCircles, 16, false, false},
	{Circles, Seven, SevenOfCircles, 17, false, false},
	{Circles, Eight, EightOfCircles, 18, false, false},
	{Circles, Nine, NineOfCircles, 19, false, false},

	{Circles, One, OneOfCircles, 11, false, false},
	{Circles, Two, TwoOfCircles, 12, false, false},
	{Circles, Three, ThreeOfCircles, 13, false, false},
	{Circles, Four, FourOfCircles, 14, false, false},
	{Circles, Five, FiveOfCircles, 15, false, false},
	{Circles, Six, SixOfCircles, 16, false, false},
	{Circles, Seven, SevenOfCircles, 17, false, false},
	{Circles, Eight, EightOfCircles, 18, false, false},
	{Circles, Nine, NineOfCircles, 19, false, false},

	{Circles, One, OneOfCircles, 11, false, false},
	{Circles, Two, TwoOfCircles, 12, false, false},
	{Circles, Three, ThreeOfCircles, 13, false, false},
	{Circles, Four, FourOfCircles, 14, false, false},
	{Circles, Five, FiveOfCircles, 15, false, false},
	{Circles, Six, SixOfCircles, 16, false, false},
	{Circles, Seven, SevenOfCircles, 17, false, false},
	{Circles, Eight, EightOfCircles, 18, false, false},
	{Circles, Nine, NineOfCircles, 19, false, false},

	{Circles, One, OneOfCircles, 11, false, false},
	{Circles, Two, TwoOfCircles, 12, false, false},
	{Circles, Three, ThreeOfCircles, 13, false, false},
	{Circles, Four, FourOfCircles, 14, false, false},
	{Circles, Five, FiveOfCircles, 15, false, false},
	{Circles, Six, SixOfCircles, 16, false, false},
	{Circles, Seven, SevenOfCircles, 17, false, false},
	{Circles, Eight, EightOfCircles, 18, false, false},
	{Circles, Nine, NineOfCircles, 19, false, false},

	{Bamboos, One, OneOfBamboos, 21, false, false},
	{Bamboos, Two, TwoOfBamboos, 22, false, false},
	{Bamboos, Three, ThreeOfBamboos, 23, false, false},
	{Bamboos, Four, FourOfBamboos, 24, false, false},
	{Bamboos, Five, FiveOfBamboos, 25, false, false},
	{Bamboos, Six, SixOfBamboos, 26, false, false},
	{Bamboos, Seven, SevenOfBamboos, 27, false, false},
	{Bamboos, Eight, EightOfBamboos, 28, false, false},
	{Bamboos, Nine, NineOfBamboos, 29, false, false},

	{Bamboos, One, OneOfBamboos, 21, false, false},
	{Bamboos, Two, TwoOfBamboos, 22, false, false},
	{Bamboos, Three, ThreeOfBamboos, 23, false, false},
	{Bamboos, Four, FourOfBamboos, 24, false, false},
	{Bamboos, Five, FiveOfBamboos, 25, false, false},
	{Bamboos, Six, SixOfBamboos, 26, false, false},
	{Bamboos, Seven, SevenOfBamboos, 27, false, false},
	{Bamboos, Eight, EightOfBamboos, 28, false, false},
	{Bamboos, Nine, NineOfBamboos, 29, false, false},

	{Bamboos, One, OneOfBamboos, 21, false, false},
	{Bamboos, Two, TwoOfBamboos, 22, false, false},
	{Bamboos, Three, ThreeOfBamboos, 23, false, false},
	{Bamboos, Four, FourOfBamboos, 24, false, false},
	{Bamboos, Five, FiveOfBamboos, 25, false, false},
	{Bamboos, Six, SixOfBamboos, 26, false, false},
	{Bamboos, Seven, SevenOfBamboos, 27, false, false},
	{Bamboos, Eight, EightOfBamboos, 28, false, false},
	{Bamboos, Nine, NineOfBamboos, 29, false, false},

	{Bamboos, One, OneOfBamboos, 21, false, false},
	{Bamboos, Two, TwoOfBamboos, 22, false, false},
	{Bamboos, Three, ThreeOfBamboos, 23, false, false},
	{Bamboos, Four, FourOfBamboos, 24, false, false},
	{Bamboos, Five, FiveOfBamboos, 25, false, false},
	{Bamboos, Six, SixOfBamboos, 26, false, false},
	{Bamboos, Seven, SevenOfBamboos, 27, false, false},
	{Bamboos, Eight, EightOfBamboos, 28, false, false},
	{Bamboos, Nine, NineOfBamboos, 29, false, false},
}

var HunTilesMap = map[int32]int32{
	EastWind:  33,
	SouthWind: 32,
	WestWind:  34,
	NorthWind: 10,

	RedDragon:   20,
	GreenDragon: 30,
	WhiteDragon: 31,

	OneOfCharacters:   2,
	TwoOfCharacters:   3,
	ThreeOfCharacters: 4,
	FourOfCharacters:  5,
	FiveOfCharacters:  6,
	SixOfCharacters:   7,
	SevenOfCharacters: 8,
	EightOfCharacters: 9,
	NineOfCharacters:  1,

	OneOfBamboos:   22,
	TwoOfBamboos:   23,
	ThreeOfBamboos: 24,
	FourOfBamboos:  25,
	FiveOfBamboos:  26,
	SixOfBamboos:   27,
	SevenOfBamboos: 28,
	EightOfBamboos: 29,
	NineOfBamboos:  21,

	OneOfCircles:   12,
	TwoOfCircles:   13,
	ThreeOfCircles: 14,
	FourOfCircles:  15,
	FiveOfCircles:  16,
	SixOfCircles:   17,
	SevenOfCircles: 18,
	EightOfCircles: 19,
	NineOfCircles:  11,
}
